TRUNCATE Account CASCADE;
insert into Account (uid, password) values ('mbohling0', '9bszXAgmdj');
insert into Account (uid, password) values ('rkettleson1', 'sjPbJsbeg');
insert into Account (uid, password) values ('cupwood2', '4eaPqEZX2');
insert into Account (uid, password) values ('sguilder3', 'P3eGrPRD');
insert into Account (uid, password) values ('ffurnell4', 'KOFTWAtk5iM');
insert into Account (uid, password) values ('dsproston5', 'EEgn2q');
insert into Account (uid, password) values ('bdibson6', 'edjUqJwc1');
insert into Account (uid, password) values ('jsalzburg7', 'myj2YVFc8zK');
insert into Account (uid, password) values ('bgorelli8', 'cnnS4ZAZV');
insert into Account (uid, password) values ('mfritschmann9', 'UGqu4ts9FO');
insert into Account (uid, password) values ('cconstanzaa', 'sIMs2aMUF');
insert into Account (uid, password) values ('wbarreaub', 'E6R2sMAlmDs');
insert into Account (uid, password) values ('cthurleyc', 'ZW0bHB1dOn');
insert into Account (uid, password) values ('zattwaterd', 'yqf7X3Uk0z');
insert into Account (uid, password) values ('lmcbeathe', '8IqEMMXBn5');
insert into Account (uid, password) values ('scheeversf', 'fU09GV');
insert into Account (uid, password) values ('jvaltig', 'SrQqTjOfWNyL');
insert into Account (uid, password) values ('ctitchardh', 'M2BJfE');
insert into Account (uid, password) values ('rcracoei', 'Xmnn0gTA');
insert into Account (uid, password) values ('gbloodj', 'sBtC9bUdy');
insert into Account (uid, password) values ('rjurkowskik', 'EigFC54');
insert into Account (uid, password) values ('mmorpethl', 'SyeYkDw');
insert into Account (uid, password) values ('wzellandm', 'BeU29Uo');
insert into Account (uid, password) values ('fkobierskin', 'Bn6nBvqtaoDU');
insert into Account (uid, password) values ('lswyno', 't6GXuF');
insert into Account (uid, password) values ('dewolsp', 'xzewVL');
insert into Account (uid, password) values ('oportwaineq', '3SY0hGNyccBR');
insert into Account (uid, password) values ('aavrahamofr', '35UJo4');
insert into Account (uid, password) values ('hbrongers', 'lLFCQs2');
insert into Account (uid, password) values ('likint', 'sRxrMqeRV3');
insert into Account (uid, password) values ('afilipowiczu', 'ZsEmG3');
insert into Account (uid, password) values ('acarverv', 'MDWy5Qq8l');
insert into Account (uid, password) values ('tblazhevichw', '4zqM03yF');
insert into Account (uid, password) values ('gfutterx', 'R28Y7g');
insert into Account (uid, password) values ('agregoriy', 'hgEnGp08tp');
insert into Account (uid, password) values ('mlerwillz', 'yDqhEyNC');
insert into Account (uid, password) values ('ceadington10', '3WlpSefs');
insert into Account (uid, password) values ('mgaskal11', 'U5fugf9Oxwaz');
insert into Account (uid, password) values ('smacy12', 'h9spWP4195Pr');
insert into Account (uid, password) values ('dyeliashev13', '2tSTqi1ePd');
insert into Account (uid, password) values ('nmuggach14', 'X2lVrHX1');
insert into Account (uid, password) values ('wtsar15', 'AmO5HVq1yh');
insert into Account (uid, password) values ('rcampos16', 'b2ibAUWASejk');
insert into Account (uid, password) values ('sjane17', '42hEFN9qE7');
insert into Account (uid, password) values ('klimpricht18', 'MOHxrS1thmx');
insert into Account (uid, password) values ('erook19', 'nwqso3RDg');
insert into Account (uid, password) values ('alytle1a', 'tESCy4t');
insert into Account (uid, password) values ('lbegley1b', 'ahZKUcQTIhE');
insert into Account (uid, password) values ('carntzen1c', 'ZkzknmIMFF');
insert into Account (uid, password) values ('lhalversen1d', 'GU1UvcI02vGu');

TRUNCATE Users CASCADE;
insert into Users (uid, email, address, mobile) values ('mbohling0', 'sbruckenthal0@netscape.com', '2 Ridge Oak Avenue', '7401775660');
insert into Users (uid, email, address, mobile) values ('rkettleson1', 'bgauge1@google.com.br', '02453 Pond Way', '8578924442');
insert into Users (uid, email, address, mobile) values ('cupwood2', 'gvilla2@edublogs.org', '03 New Castle Circle', '1241633207');
insert into Users (uid, email, address, mobile) values ('sguilder3', 'dkibbye3@nbcnews.com', '4523 Marcy Way', '4614554104');
insert into Users (uid, email, address, mobile) values ('ffurnell4', 'kdegue4@dyndns.org', '80 North Way', '1619725218');
insert into Users (uid, email, address, mobile) values ('dsproston5', 'nonoland5@bluehost.com', '13969 Lake View Road', '1717855535');
insert into Users (uid, email, address, mobile) values ('bdibson6', 'dholson6@skyrock.com', '1775 Eggendart Lane', '3886214840');
insert into Users (uid, email, address, mobile) values ('jsalzburg7', 'ldominy7@umich.edu', '3 Lake View Road', '7035757696');
insert into Users (uid, email, address, mobile) values ('bgorelli8', 'bcubuzzi8@businessinsider.com', '4354 Graedel Hill', '6795329126');
insert into Users (uid, email, address, mobile) values ('mfritschmann9', 'lmcwhirter9@wunderground.com', '53 Pierstorff Parkway', '9799423182');
insert into Users (uid, email, address, mobile) values ('cconstanzaa', 'cclampetta@nifty.com', '18 Mariners Cove Street', '9661938410');
insert into Users (uid, email, address, mobile) values ('wbarreaub', 'mhaldeneb@yellowbook.com', '0 Northridge Lane', '2402474115');
insert into Users (uid, email, address, mobile) values ('cthurleyc', 'wbosquetc@unblog.fr', '20 Dixon Place', '7857530905');
insert into Users (uid, email, address, mobile) values ('zattwaterd', 'kjewerd@seesaa.net', '200 Golf View Park', '4653140873');
insert into Users (uid, email, address, mobile) values ('lmcbeathe', 'sjopkee@issuu.com', '29234 Everett Avenue', '8307620324');
insert into Users (uid, email, address, mobile) values ('scheeversf', 'lknowlysf@parallels.com', '9 Clyde Gallagher Court', '3215188110');
insert into Users (uid, email, address, mobile) values ('jvaltig', 'agatrillg@ftc.gov', '9037 Mitchell Way', '7118732028');
insert into Users (uid, email, address, mobile) values ('ctitchardh', 'fdarwinh@globo.com', '8091 Kipling Point', '9507233589');
insert into Users (uid, email, address, mobile) values ('rcracoei', 'dmargetti@cargocollective.com', '9388 Heffernan Center', '3348937039');
insert into Users (uid, email, address, mobile) values ('gbloodj', 'msinnattj@opensource.org', '63 Eliot Crossing', '9174452620');
insert into Users (uid, email, address, mobile) values ('rjurkowskik', 'dridehalghk@bloglines.com', '2899 Meadow Valley Place', '5217034151');
insert into Users (uid, email, address, mobile) values ('mmorpethl', 'dangoodl@deviantart.com', '3435 Bay Way', '5529980244');
insert into Users (uid, email, address, mobile) values ('wzellandm', 'raggettm@sciencedaily.com', '3994 Vera Lane', '5462639017');
insert into Users (uid, email, address, mobile) values ('fkobierskin', 'hheildsn@ow.ly', '2 Montana Junction', '9009098581');
insert into Users (uid, email, address, mobile) values ('lswyno', 'bbridalo@nih.gov', '70845 Tomscot Avenue', '7487917278');
insert into Users (uid, email, address, mobile) values ('dewolsp', 'gmenurep@1und1.de', '4 1st Trail', '7367164467');
insert into Users (uid, email, address, mobile) values ('oportwaineq', 'kbrussellq@utexas.edu', '83 Michigan Way', '2304459763');
insert into Users (uid, email, address, mobile) values ('aavrahamofr', 'nwalcarr@arizona.edu', '99 Acker Junction', '1117458620');
insert into Users (uid, email, address, mobile) values ('hbrongers', 'cshipleys@webnode.com', '76456 Oak Park', '1923165031');
insert into Users (uid, email, address, mobile) values ('likint', 'rulyatt@jimdo.com', '470 Grasskamp Place', '4615922700');
insert into Users (uid, email, address, mobile) values ('afilipowiczu', 'koffneru@gov.uk', '397 Canary Terrace', '5466447932');
insert into Users (uid, email, address, mobile) values ('acarverv', 'rdegowev@businesswire.com', '8 Londonderry Drive', '6128883206');
insert into Users (uid, email, address, mobile) values ('tblazhevichw', 'srayltonw@unesco.org', '689 Washington Hill', '3534867779');
insert into Users (uid, email, address, mobile) values ('gfutterx', 'lpercivalx@163.com', '49 Sugar Center', '6238162467');
insert into Users (uid, email, address, mobile) values ('agregoriy', 'eewencey@mozilla.com', '492 Crest Line Drive', '7415274092');
insert into Users (uid, email, address, mobile) values ('mlerwillz', 'hlawleez@t-online.de', '864 Briar Crest Point', '3943118492');
insert into Users (uid, email, address, mobile) values ('ceadington10', 'mdowd10@home.pl', '37573 Spohn Circle', '5263753306');
insert into Users (uid, email, address, mobile) values ('mgaskal11', 'cbracher11@cdbaby.com', '16813 Cambridge Avenue', '8015170841');
insert into Users (uid, email, address, mobile) values ('smacy12', 'syakubovich12@google.com.br', '2170 Messerschmidt Park', '1892734980');
insert into Users (uid, email, address, mobile) values ('dyeliashev13', 'ofumagall13@hatena.ne.jp', '7476 Dryden Avenue', '6344171294');
insert into Users (uid, email, address, mobile) values ('nmuggach14', 'hlamke14@networkadvertising.org', '1531 Bay Street', '2494076308');
insert into Users (uid, email, address, mobile) values ('wtsar15', 'anaire15@yahoo.co.jp', '3 Monument Terrace', '5705689513');
insert into Users (uid, email, address, mobile) values ('rcampos16', 'jbolens16@mit.edu', '931 Hollow Ridge Park', '8947076759');
insert into Users (uid, email, address, mobile) values ('sjane17', 'nleeds17@fda.gov', '2450 Oxford Parkway', '4636614608');
insert into Users (uid, email, address, mobile) values ('klimpricht18', 'chasslocher18@booking.com', '0 Westend Court', '2837156500');
insert into Users (uid, email, address, mobile) values ('erook19', 'rhuxley19@slideshare.net', '4030 Hintze Crossing', '5522250288');
insert into Users (uid, email, address, mobile) values ('alytle1a', 'bkinnear1a@usda.gov', '971 Gina Center', '7804874311');
insert into Users (uid, email, address, mobile) values ('lbegley1b', 'gbryde1b@apple.com', '63144 Clove Circle', '2046928732');
insert into Users (uid, email, address, mobile) values ('carntzen1c', 'yworling1c@tinyurl.com', '83 Russell Junction', '2701547826');
insert into Users (uid, email, address, mobile) values ('lhalversen1d', 'mdownham1d@marketwatch.com', '285 Bobwhite Trail', '8763235436');